set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_CROSSCOMPILING TRUE)
set(CMAKE_SYSTEM_PROCESSOR avr)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

file(GLOB AVR_SYSTEM_DIRS "$ENV{HOME}/.arduino*/packages/arduino")
list(GET AVR_SYSTEM_DIRS -1 AVR_SYSTEM_DIR)

file(GLOB AVR_TC_DIRS "${AVR_SYSTEM_DIR}/tools/avr-gcc/*/bin")
list(GET AVR_TC_DIRS -1 AVR_TC_DIR)

file(GLOB AVR_HW_DIRS "${AVR_SYSTEM_DIR}/hardware/avr/*")
list(GET AVR_HW_DIRS -1 AVR_HW_DIR)

set(CMAKE_C_COMPILER "${AVR_TC_DIR}/avr-gcc")
set(CMAKE_C_STANDARD 17)
set(CMAKE_C_EXTENSIONS ON)

set(CMAKE_CXX_COMPILER "${AVR_TC_DIR}/avr-g++")
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_EXTENSIONS ON)

set(CMAKE_OBJCOPY "${AVR_TC_DIR}/avr-objcopy")
set(CMAKE_SIZE "${AVR_TC_DIR}/avr-size")
